Updated POT accounting scripts for new trigger fragment definition
SBNSoftware/sbncode pull request #321
Opened 2022-12-01 23:19 UTC by jzettle

This PR updates the POT accounting scripts to handle new information from an updated trigger fragment definition ICARUSTriggerV3 that was requested to split the trigger gate counting for majority and minbias streams. This code may get updated as it gets fully vetted and tested which I hope to complete tonight or at the latest tomorrow morning. The idea is this code is backwards compatible and should work with any data taken with ICARUSTriggerV3 or ICARUSTriggerV2 (the current implementation) but this piece need to be confirmed working. This PR is combined with ones on icaruscode and the offline branch of sbndaq-artdaq-core and I will update this once everything is in place and link to those. 

I understand this is important for Run2 data taking and I may need emergency help dealing with any version update issues as this is related to an older version of sbncode at this point but this has been a long project where I did not have a good opportunity to update this until it was done.

2022-12-02 14:31 UTC, wesketchum approved these changes
looks good to me

2022-12-02 15:24 UTC, FNALbuild commented
:heavy_check_mark: CI build for LArSoft Succeeded on slf7 for e20:prof -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app//view_builds/index?offset=0&builds=lar_ci/17689&builds=)

2022-12-02 15:38 UTC, FNALbuild commented
:heavy_check_mark: CI build for LArSoft Succeeded on slf7 for c7:prof -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app//view_builds/index?offset=0&builds=lar_ci/17688&builds=)

2022-12-02 16:12 UTC, FNALbuild commented
:x: CI build for SBND Failed at phase ci_tests SBND on slf7 for e20:prof - ignored warnings for build -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/ns:SBND/view_builds/index?offset=0&builds=sbnd_ci/10770&builds=)

:rotating_light: For more details about the failed phase, check the [ci_tests SBND phase logs](https://dbweb0.fnal.gov/LarCI/app/ns:SBND/build_detail/phase_details?build_id=sbnd_ci/10770&platform=Linux%203.10.0-1160.76.1.el7.x86_64&phase=ci_tests&buildtype=slf7%20e20:prof)

parent CI build details are available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/view_builds/index?offset=0&builds=lar_ci/17689&builds=)

2022-12-02 16:22 UTC, FNALbuild commented
:x: CI build for SBND Failed at phase ci_tests SBND on slf7 for c7:prof - ignored warnings for build -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/ns:SBND/view_builds/index?offset=0&builds=sbnd_ci/10771&builds=)

:rotating_light: For more details about the failed phase, check the [ci_tests SBND phase logs](https://dbweb0.fnal.gov/LarCI/app/ns:SBND/build_detail/phase_details?build_id=sbnd_ci/10771&platform=Linux%203.10.0-1160.76.1.el7.x86_64&phase=ci_tests&buildtype=slf7%20c7:prof)

parent CI build details are available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/view_builds/index?offset=0&builds=lar_ci/17688&builds=)

2022-12-02 16:32 UTC, FNALbuild commented
:x: CI build for ICARUS Failed at phase build ICARUS on slf7 for c7:prof -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/ns:ICARUS/view_builds/index?offset=0&builds=icarus_ci/5831&builds=)

:rotating_light: For more details about the failed phase, check the [build ICARUS phase logs](https://dbweb0.fnal.gov/LarCI/app/ns:ICARUS/build_detail/phase_details?build_id=icarus_ci/5831&platform=Linux%203.10.0-1160.71.1.el7.x86_64&phase=build&buildtype=slf7%20c7:prof)

parent CI build details are available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/view_builds/index?offset=0&builds=lar_ci/17688&builds=)

2022-12-02 18:07 UTC, jzettle commented
Okay @miquelnebot I have rebased the icaruscode PR also to the SBN2022B branch and resolved the conflict it had there. Thanks for your patience and your help

2022-12-24 01:10 UTC, PetrilloAtWork requested changes
I think there is an issue with `t_current_event` in the code: please take a look at it.
I am not going to hammer on the form of the code because this is supposed to be temporary, while the final form should use `sbn::ExtraTriggerInfo`.

2022-12-24 01:10 UTC, PetrilloAtWork commented on sbncode/BeamSpillInfoRetriever/NuMIRetriever/NuMIRetriever_module.cc
> +    unsigned int number_of_gates_since_previous_event = 0; // FIXME needs to be integral type
```cpp
    unsigned int number_of_gates_since_previous_event = 0; // FIXME needs to be integral type                        
```
What does the comment mean? this variable is already an integral type.

2022-12-24 01:10 UTC, PetrilloAtWork commented on sbncode/BeamSpillInfoRetriever/NuMIRetriever/NuMIRetriever_module.cc
> +      triggerInfo.t_current_event = static_cast<double>(artdaq_ts)/(1000000000.0);
Same comment as above, here and in the next `if` statement.

2023-07-17 17:21 UTC, closed without merging