Feature/gputnam configs
SBNSoftware/sbncode pull request #391
Opened 2023-10-22 01:52 UTC by gputnam

2024-01-17 17:22 UTC, jzennamo commented
@gputnam it might help to base your branch off of my branch here:
https://github.com/SBNSoftware/sbncode/pull/394 

this has many similar changes as your PR

2024-01-17 18:59 UTC, jzennamo requested changes
Looks good, I might base your PR off my other PR

2024-01-17 18:59 UTC, jzennamo commented on sbncode/SBNEventWeight/Calculators/Geant4/Geant4WeightCalc.cxx
> +        tmp_vals[FitParNames.at(i_parset)] = FitParNominals.at(i_parset)+(FitParSigmas.at(i_parset)*r);
What is this supposed to be doing? I guess I just am not sure what `FitParSigmas.at(i_parset)` is supposed to be in this case

2024-01-17 18:59 UTC, jzennamo commented on sbncode/SBNEventWeight/Calculators/Geant4/Geant4WeightCalc.cxx
> +    else if( p_PDG == 2212 ) mass = 938.28;
Doesn't `simb::MCParticle` have the `Mass()` is there a reason to not use that?

2024-01-17 18:59 UTC, jzennamo commented on sbncode/SBNEventWeight/Calculators/Geant4/Geant4WeightCalc.cxx
> +          if (test_mcp->TrackId() == daughterID){
I thought `daughterID` was the location in the array of the `.Daughter(i_mcp)` and not the trackID:
https://internal.dunescience.org/doxygen/MCParticle_8cxx_source.html#l00112

2024-01-17 18:59 UTC, jzennamo commented on sbncode/SBNEventWeight/Calculators/Geant4/Geant4WeightCalc.cxx
> +        );
```suggestion
        double len = std::hypot(deltaX, deltaY, deltaZ);
```

2024-01-17 18:59 UTC, jzennamo commented on sbncode/SBNEventWeight/Calculators/Geant4/Geant4WeightCalc.cxx
> +        weight[j] *= std::max((float)0.0, w);
should this be the max between 1 and w?

2024-01-17 18:59 UTC, jzennamo commented on sbncode/SBNEventWeight/Calculators/Geant4/Geant4WeightCalc.cxx
> +        weight[j] *= std::max((float)0.0,el_w);
should this be the max between 1 and w?

2024-01-17 18:59 UTC, jzennamo commented on sbncode/SBNEventWeight/jobs/geant4/eventweight_geant4_sbn.fcl
Only comment is that maybe the random seeds should be a bit more....random ;)

2024-01-17 18:59 UTC, jzennamo commented on sbncode/SBNEventWeight/jobs/geant4/piplus_reweight_parameters.fcl
> +    Nominal:    1
```suggestion
    Nominal:    1.0
```

2024-01-17 18:59 UTC, jzennamo commented on sbncode/SBNEventWeight/jobs/geant4/proton_reweight_parameters.fcl
> +    Nominal:    1
```suggestion
    Nominal:    1.0
```

2024-02-05 22:26 UTC, gputnam commented
This PR has now been superseded by a combination of other PRs, most recently: https://github.com/SBNSoftware/sbncode/pull/417, https://github.com/SBNSoftware/sbncode/pull/418/files, and https://github.com/SBNSoftware/sbncode/pull/419. Closing this in favor of those.

2024-02-05 22:26 UTC, closed without merging