Updated Flux files for the HNL simulation using the Kaon BNB flux
SBNSoftware/sbncode pull request #432
Opened 2024-02-19 22:42 UTC by rodralva

Re weighted flux files in boone ntuple format to keep up with most  recent SciBooNE measures. I collaborated with Zarko Pavlovic to make the reweigh of the original files. More info can be found in [docdb 31883](
https://sbn-docdb.fnal.gov/cgi-bin/sso/ShowDocument?docid=31883).
The code, previous files and re weighted flux files can be found in:
`/cvmfs/sbn.osgstorage.org/pnfs/fnal.gov/usr/sbn/persistent/stash/physics-rodrigoa/bnbflux/`
To make sure reweigh was properly done, validation plots like this one were performed in different kinematic variables, showing a small difference within 5%, which was the expected behavior.
![image](https://github.com/SBNSoftware/sbncode/assets/70945401/b11054db-bd98-4475-9a79-931c2be1f0af)

2024-02-19 23:08 UTC, VCLanNguyen approved these changes

2024-02-19 23:36 UTC, jicrespo requested changes
The `bnb_kaon_common.fcl` file should contain only the common part to SBND and ICARUS. All the variables that contain `sbnd` in their names should be defined in `sbndcode` or in a fcl file labeled as "sbnd".

2024-02-20 01:58 UTC, rodralva commented
Updated both PRs with @jicrespo suggestion, I separated the generic stuff (bnb_kaon_common.fcl) and sbnd specific (bnb_kaon_sbnd) in 2 different files for clarity.

2024-02-20 17:02 UTC, FNALbuild commented
:heavy_check_mark: CI build for LArSoft Succeeded on slf7 for c14:prof -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app//view_builds/index?offset=0&builds=lar_ci/21893&builds=)

2024-02-20 17:11 UTC, jicrespo approved these changes

2024-02-20 17:15 UTC, FNALbuild commented
:x: CI build for SBND Failed at phase unit_test SBND on slf7 for c14:prof - ignored warnings for build -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/ns:SBND/view_builds/index?offset=0&builds=sbnd_ci/13636&builds=)

:rotating_light: For more details about the failed phase, check the [unit_test SBND phase logs](https://dbweb0.fnal.gov/LarCI/app/ns:SBND/build_detail/phase_details?build_id=sbnd_ci/13636&platform=Linux%203.10.0-1160.102.1.el7.x86_64&phase=unit_test&buildtype=slf7%20c14:prof)

parent CI build details are available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/view_builds/index?offset=0&builds=lar_ci/21893&builds=)

2024-02-20 17:40 UTC, FNALbuild commented
:warning: CI build for ICARUS Warning at phase ci_tests ICARUS on slf7 for e26:prof -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/ns:ICARUS/view_builds/index?offset=0&builds=icarus_ci/9276&builds=)

:rotating_light: For more details about the warning phase, check the [ci_tests ICARUS phase logs](https://dbweb0.fnal.gov/LarCI/app/ns:ICARUS/build_detail/phase_details?build_id=icarus_ci/9276&platform=Linux%203.10.0-1160.102.1.el7.x86_64&phase=ci_tests&buildtype=slf7%20e26:prof)

parent CI build details are available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/view_builds/index?offset=0&builds=lar_ci/21894&builds=)

2024-02-20 17:46 UTC, FNALbuild commented
:warning: CI build for SBND Warning at phase ci_tests SBND on slf7 for e26:prof - ignored warnings for build -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/ns:SBND/view_builds/index?offset=0&builds=sbnd_ci/13637&builds=)

:rotating_light: For more details about the warning phase, check the [ci_tests SBND phase logs](https://dbweb0.fnal.gov/LarCI/app/ns:SBND/build_detail/phase_details?build_id=sbnd_ci/13637&platform=Linux%203.10.0-1160.102.1.el7.x86_64&phase=ci_tests&buildtype=slf7%20e26:prof)

parent CI build details are available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/view_builds/index?offset=0&builds=lar_ci/21894&builds=)

2024-02-20 18:02 UTC, FNALbuild commented
:x: CI build for ICARUS Failed at phase ci_tests ICARUS on slf7 for c14:prof - ignored failure for unit_test -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/ns:ICARUS/view_builds/index?offset=0&builds=icarus_ci/9275&builds=)

:rotating_light: For more details about the failed phase, check the [ci_tests ICARUS phase logs](https://dbweb0.fnal.gov/LarCI/app/ns:ICARUS/build_detail/phase_details?build_id=icarus_ci/9275&platform=Linux%203.10.0-1160.102.1.el7.x86_64&phase=ci_tests&buildtype=slf7%20c14:prof)

parent CI build details are available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/view_builds/index?offset=0&builds=lar_ci/21893&builds=)

2024-02-21 14:27 UTC, merged