Feature/jskim adding genie tree to caf sbn2024 a
SBNSoftware/sbncode pull request #478
Opened 2024-10-22 21:35 UTC by jedori0228

This is a copy of https://github.com/SBNSoftware/sbncode/pull/459 (on develop) or https://github.com/SBNSoftware/sbncode/pull/426 (on release/SBN2023A_NuMI).

Saving `genie::EventRecord` as a separate `TTree` into `CAFs`. By default we do not save it, and we turn this feature by adding `physics.producers.cafmaker.SaveGENIEEventRecord: true` in fhicls.
The matching between a `SRTrueInteraction` object from `recTree` and `genie::EventRecord` is done by the index of genie tree, `genie_evtrec_idx`, which is introduced in

2024-10-23 00:39 UTC, jacoblarkin approved these changes
Thanks Jaesung!

2024-11-19 16:37 UTC, PetrilloAtWork requested changes
All good except for a question on the `CMakeLists.txt`.

2024-11-19 16:37 UTC, PetrilloAtWork commented on sbncode/CAFMaker/CMakeLists.txt
> +                  ${GENIE_LIB_LIST}
Where is this variable defined? is it necessary?
You may also ask CMake to print its value (I think something like `message(STATUS "GENIE_LIB_LIST='${GENIE_LIB_LIST}'")`).
If this variable is empty or unnecessary, we should not put it (they often go viral).

2024-12-03 02:18 UTC, PetrilloAtWork commented on sbncode/CAFMaker/CMakeLists.txt
> +                  ${GENIE_LIB_LIST}
Thank you for finding that. It's not really a standard pattern (in fact, I question it), but it's valid.

2024-12-03 02:19 UTC, PetrilloAtWork approved these changes
Approved after clarification by the requester.

2024-12-03 12:48 UTC, etworcester approved these changes
Thanks (and sorry for the delay - I missed that I was tagged on this one)

2024-12-09 16:44 UTC, merged